services:
    superlog-php:
        container_name: superlog-php
        build:
            target: dev
        environment:
            DEPLOY_CMD: "tail -f /dev/null"
        volumes:
            - '.:/var/www/html'
